# Generated by Django 2.2.3 on 2019-07-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_auto_20190723_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WaterSheds',
            new_name='WaterShedsHUC2',
        ),
    ]
