# Generated by Django 3.1.2 on 2020-10-19 05:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HUC2',
            fields=[
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=255)),
                ('tnmid', models.CharField(max_length=255)),
                ('huc_id', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HUC4',
            fields=[
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=255)),
                ('tnmid', models.CharField(max_length=255)),
                ('huc_id', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('lower_huc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huc4', to='api.huc2')),
            ],
        ),
        migrations.CreateModel(
            name='HUC6',
            fields=[
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=255)),
                ('tnmid', models.CharField(max_length=255)),
                ('huc_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('lower_huc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huc6', to='api.huc4')),
            ],
        ),
        migrations.CreateModel(
            name='HUC8',
            fields=[
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.CharField(max_length=255)),
                ('tnmid', models.CharField(max_length=255)),
                ('huc_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('lower_huc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huc8', to='api.huc6')),
            ],
        ),
    ]
