# Generated by Django 2.2.3 on 2019-07-23 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_auto_20190723_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaterShedsHUC2',
        ),
    ]
