# Generated by Django 2.2.3 on 2019-07-23 11:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0008_watersheds'),
    ]

    operations = [
        migrations.CreateModel(
            name='HUC2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tnmid', models.CharField(max_length=255, unique=True)),
                ('huc2_id', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HUC4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tnmid', models.CharField(max_length=255, unique=True)),
                ('huc4_id', models.CharField(max_length=4, unique=True)),
                ('huc2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huc4', to='reporter.HUC2')),
            ],
        ),
        migrations.DeleteModel(
            name='WaterSheds',
        ),
    ]
