# Generated by Django 2.2.3 on 2019-07-23 11:59

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0009_auto_20190723_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huc2',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
