# Generated by Django 2.2.3 on 2019-07-24 15:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0011_auto_20190723_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='HUC6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tnmid', models.CharField(max_length=255, unique=True)),
                ('huc6_id', models.CharField(max_length=6, unique=True)),
                ('huc4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huc6', to='reporter.HUC4')),
            ],
        ),
        migrations.CreateModel(
            name='HUC8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('tnmid', models.CharField(max_length=255, unique=True)),
                ('huc8_id', models.CharField(max_length=8, unique=True)),
                ('huc6', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='huc8', to='reporter.HUC6')),
            ],
        ),
        migrations.DeleteModel(
            name='Counties',
        ),
        migrations.DeleteModel(
            name='Incidences',
        ),
    ]
