# Generated by Django 3.0.7 on 2020-07-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0017_auto_20200713_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huc2',
            name='id',
        ),
        migrations.RemoveField(
            model_name='huc4',
            name='id',
        ),
        migrations.RemoveField(
            model_name='huc6',
            name='id',
        ),
        migrations.RemoveField(
            model_name='huc8',
            name='id',
        ),
        migrations.AlterField(
            model_name='huc2',
            name='huc_id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='huc2',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='huc2',
            name='tnmid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='huc4',
            name='huc_id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='huc4',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='huc4',
            name='tnmid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='huc6',
            name='huc_id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='huc6',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='huc6',
            name='tnmid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='huc8',
            name='huc_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='huc8',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='huc8',
            name='tnmid',
            field=models.CharField(max_length=255),
        ),
    ]
